version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_TYPE: sqlite
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME:
      DB_PASSWORD:
      DB_NAME: database.sqlite
      MONGO_URL: mongodb://mongo:27017/eventstore
      JWT_SECRET: your-secret-key
    restart: unless-stopped
  
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: